---
title: "extract_crowns_data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{extract_crowns_data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, results='hide', message=FALSE, warning=FALSE}
library(managecrownsdata)
library(dplyr)
library(stringr)
library(sf)
library(DT)
library(terra)
```

Extracting rgb crowns data requires rgb mosaics and 
```{r message=FALSE, warning=FALSE, results='hide'}
crownsFile <- sf::st_read(file.path(system.file(package="managecrownsdata"), '/crowns/crowns_test.gpkg'))
rgb_paths <- list.files(file.path(system.file(package="managecrownsdata"), 'rgb/'), full.names = TRUE)
dates <- paste(
   stringr::str_sub(stringr::str_split(basename(rgb_paths), '_', simplify = TRUE)[,2],1,4),
   stringr::str_sub(stringr::str_split(basename(rgb_paths), '_', simplify = TRUE)[,2],5,6),
   stringr::str_sub(stringr::str_split(basename(rgb_paths), '_', simplify = TRUE)[,2],7,8),
   sep = '_'
)
site = 'Bouamir'
crs <- 'EPSG:32633'
```

```{r}
check_crownsFile(crownsFile = crownsFile)
```

```{r}
crownsFile <- crownsFile %>% dplyr::rename(geometry = geom,
                      family = tax_fam,
                      genus = tax_gen,
                      specie = tx_sp_lvl,
                      code_sp = idtax_f)
```

```{r}
check_crownsFile(crownsFile = crownsFile)
```

```{r, fig.width=9, fig.height=9}

x <- terra::rast(rgb_paths[1])

terra::plotRGB(
   x,
   main = dates[1],
   axes = T,
   mar = 2
)

base::plot(crownsFile$geometry,
           border = "red",
           lwd = 2,
           add = TRUE)
terra::text(terra::vect(crownsFile), labels="id", col = 'blue', cex = 2)

```

```{r, results='hide'}

rgb_extraction <- extract_rgbValues(
      crownsFile = crownsFile,
      path_images = rgb_paths,
      site = site,
      dates = dates,
      crs = crs,
      fun = 'all'
   )

```

```{r}
datatable(rgb_extraction, 
          class = 'cell-border stripe',
          rownames = FALSE,
          width = '100%', 
          options = list(scrollX = TRUE))
```
