name: R-CMD-check

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (R ${{ matrix.config.r }})
    strategy:
      matrix:
        config:
          - { os: ubuntu-latest, r: 'release' }
          - { os: windows-latest, r: 'release' }
          - { os: macOS-latest, r: 'release' }

    steps:
      - uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ matrix.config.r }}-1
          restore-keys: ${{ runner.os }}-r-${{ matrix.config.r }}

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install dependencies
        run: |
          install.packages('remotes')
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Check
        run: |
          devtools::check()
        shell: Rscript {0}

      - name: Upload check results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: r-cmd-check-results
          path: check

